version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
platform:
- x64
- x86
build:
  project: sudo-windows.sln
  verbosity: minimal
artifacts:
- path: x64\Release\sudo-windows.exe
  name: sudo
- path: Win32\Release\sudo-windows.exe
  name: sudo-x86
deploy:
- provider: GitHub
  auth_token:
    secure: Da1U94crLYqT0h+UmW375Dq9oCS4vYxOX29Bnyzafr3EbRBwN3aCPDo9kWl/PHaq
