[package]
name = "sudo-windows"
version = "0.1.0"
authors = ["jingyu9575 <qw2g64@zoho.eu>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = [
	"winbase", "winuser", "wincon", "shellapi", "synchapi", "handleapi", "processthreadsapi"
] }
url = "1.7"